name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - input
  repository_dispatch:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            PROXYIP
            RPROXYIP
            SHA224PASS
            PASSWORD
        env:
          PROXYIP: ${{ secrets.PROXYIP }}
          RPROXYIP: ${{ secrets.RPROXYIP }}
          SHA224PASS: ${{secrets.SHA224PASS}}
          PASSWORD: ${{secrets.PASSWORD}}